import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
//https://api.rawg.io/api/games?key=bc1c2e51bf4d42acab01e84969eb1429

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <Header />
        {children}
      </body>
    </html>
  );
}
